name: release

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release please
      id: release
      uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
    - name: clone repository
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: configure npm
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
        scope: '@0xdbe'
    - name: publish package
      if: ${{ steps.release.outputs.releases_created == 'true' }}
      run: npm publish --access public